### ISSUE TITLE
How do I put the lidar(hokuyo) on the go1 robot?

### ISSUE THREAD

**Issue by juno100** [chvmp/robots#12]
i want to slam demo with go1 robot

but it don't have lidar in gazebo

so how do i put the lidar on the go1 robot?

**Comment by grassjelly** [comment]
You can add this to go1's description file: https://github.com/chvmp/champ/blob/master/champ_description/urdf/champ.urdf#L40-L96 .  Change the parent link to where you want it to be attached

**Comment by juno100** [comment]
so cooool! thank you very much!
